### ISSUE TITLE
improve examples

### ISSUE THREAD

**Issue by mkinney** [pyinfra-dev/pyinfra#287]
**Is your feature request related to a problem? Please describe.**
The examples needs some review/update/cleaning.

**Describe the solution you'd like**
Improve the files in the examples directory. Perhaps remove bats and re-write in pure python. I have found that bats on mac behaved differently on an ubuntu instance. Most of the bats files were tests, so see if that could be improved/documented better.

Edit: Please assign this issue to me. (I don't see how I can do that myself.)

**Comment by Fizzadar** [comment]
https://github.com/pyinfra-dev/pyinfra-examples now covers this, we can expand individual issues there as needed but it's covering the basics well.
